defaultPortal: teste_git
portals:
  - name: teste_git
    portalId: 20754213
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIaC8afQLxIJAA0AAAAA4A0DGKXe8gkgl5ugDCju6QwyFLJAbMWYz9BE5vek3IKoSGF3YI01OigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhRtNecfYzf1dM_BwiWFENCfliv_R0oDbmExUgBaAA
        expiresAt: '2021-11-09T13:56:20.365Z'
    personalAccessKey: >-
      CiQ5MzA5MTlkYy02YTkxLTQ1MDktOGE3OC1lNTdkOTQwNTFmZmEQpd7yCRiXm6AMKhkABeaRgroXl6TUoagyR2v8Ul1psI-qEZgvSgNuYTE
