defaultPortal: teste_git
portals:
  - name: teste_git
    portalId: 20754213
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKCR7afQLxIJAA0AAAAA4A0DGKXe8gkgl5ugDCju6QwyFOfLv_U2msSEz24pFpgRs5-ETurvOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhTt5oEKLv60n8ybwG5DSB0jCPB5wkoDbmExUgBaAA
        expiresAt: '2021-11-09T13:55:16.779Z'
    personalAccessKey: >-
      CiQ5MzA5MTlkYy02YTkxLTQ1MDktOGE3OC1lNTdkOTQwNTFmZmEQpd7yCRiXm6AMKhkABeaRgroXl6TUoagyR2v8Ul1psI-qEZgvSgNuYTE
