defaultPortal: teste_git
portals:
  - name: teste_git
    portalId: 20754213
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CI_6pajQLxIJAA0AAAAA4A0DGKXe8gkgl5ugDCju6QwyFNmlT4DpZObPZfFLo9N2kc-UijMXOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhSUE2IaVZa2KE_rNbmrzNVZi6QNpUoDbmExUgBaAA
        expiresAt: '2021-11-09T14:10:47.700Z'
    personalAccessKey: >-
      CiQ5MzA5MTlkYy02YTkxLTQ1MDktOGE3OC1lNTdkOTQwNTFmZmEQpd7yCRiXm6AMKhkABeaRgroXl6TUoagyR2v8Ul1psI-qEZgvSgNuYTE
