defaultPortal: teste_git
portals:
  - name: teste_git
    portalId: 20754213
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMz2zabQLxIJAA0AAAAA4A0DGKXe8gkgl5ugDCju6QwyFHuN0dDXxUp5qQZxCEpcWpkblYsCOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhTRZ4tKHk03vldq6599fAMgMJRC_koDbmExUgBaAA
        expiresAt: '2021-11-09T13:11:48.305Z'
    personalAccessKey: >-
      CiQ5MzA5MTlkYy02YTkxLTQ1MDktOGE3OC1lNTdkOTQwNTFmZmEQpd7yCRiXm6AMKhkABeaRgroXl6TUoagyR2v8Ul1psI-qEZgvSgNuYTE
